- name: "Ansible VMs Creations"
  hosts: localhost
  tasks:
    - 
      ec2:
        instance_tags:
          Name: Build
        assign_public_ip: true
        aws_access_key: 
        aws_secret_key: 
        count: 1
        group: devopsbc1
        image: ami-01e7ca2ef94a0ae86
        instance_type: t2.medium
        key_name: devopsbc
        region: us-east-2
        vpc_subnet_id: subnet-80db99cc
        wait: true
      name: "launching AWS instance for Deploy/Build Server"
    - 
      ec2:
        instance_tags:
          Name: Test
        assign_public_ip: true
        aws_access_key: 
        aws_secret_key: 
        count: 1
        group: devopsbc1
        image: ami-01e7ca2ef94a0ae86
        instance_type: t2.micro
        key_name: devopsbc
        region: us-east-2
        vpc_subnet_id: subnet-80db99cc
        wait: true
      name: "launching AWS instance for Test Server"
    - 
      ec2:
        instance_tags:
          Name: Prod
        assign_public_ip: true
        aws_access_key: 
        aws_secret_key: 
        count: 1
        group: devopsbc1
        image: ami-01e7ca2ef94a0ae86
        instance_type: t2.micro
        key_name: devopsbc
        region: us-east-2
        vpc_subnet_id: subnet-80db99cc
        wait: true
      name: "launching AWS instance for Prod Server"
