---
- hosts: node1
  become: yes
  tasks:
  - name: "Download the Docker script"
    get_url:
      url: https://raw.githubusercontent.com/devopsbc01/Scripts/master/dockerubuntu.sh
      dest: /dockerubuntu.sh
      mode: '7777'
  - name: "Execute the Docker script"
    shell: yes | /dockerubuntu.sh
  - name: "Modify the Jenkins user group"
    shell: sudo usermod -a -G docker jenkins
- hosts: buildANDtest
  become: yes
  tasks:
  - name: "Download the Docker script"
    get_url:
      url: https://raw.githubusercontent.com/devopsbc01/Scripts/master/dockerubuntu.sh
      dest: /dockerubuntu.sh
      mode: '7777'
  - name: "Execute the Docker script"
    shell: yes | /dockerubuntu.sh
  - name: "Pause for 10 seconds"
    pause:
      seconds: 10
